apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-wld
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/waleedcw/argo-test'
    path: helm
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - Validate=false