apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "argo.labels" . | nindent 4 }}
  name: svc-{{ include "argo.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.app_port }}
    protocol: TCP
    targetPort: {{ .Values.service.app_port }}
    nodePort: {{ .Values.service.node_port }}
  selector:
    {{- include "argo.selectorLabels" . | nindent 4 }}
  type: NodePort