# Default values for argo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# It is just a demo app with only one pod
replicaCount: 1

image:
  repository: argo
  pullPolicy: IfNotPresent
  tag: "1.12"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "argo"
namespace: "default"

selectorLabels:
  app: "argo"

service:
  node_port: 30010
  app_port: 80
